# Project: Structmethane
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = structdestr_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/dc/Dev-Cpp/MinGW64/lib32" -L"D:/dc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -mwindows -s ../../dc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32/libgdi32.a ../../dc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32/libwinmm.a ../../dc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32/libntdll.a ../../dc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32/libkernel32.a -m32
INCS     = -I"D:/dc/Dev-Cpp/MinGW64/include" -I"D:/dc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/dc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/dc/Dev-Cpp/MinGW64/include" -I"D:/dc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/dc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/dc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Structmethane.exe
CXXFLAGS = $(CXXINCS) -m32 -lgdi32 -lwinmm -lkernel32 -lntdll
CFLAGS   = $(INCS) -m32 -lgdi32 -lwinmm -lkernel32 -lntdll
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

structdestr_private.res: structdestr_private.rc 
	$(WINDRES) -i structdestr_private.rc -F pe-i386 --input-format=rc -o structdestr_private.res -O coff 

