/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef STRUCTDESTR_PRIVATE_H
#define STRUCTDESTR_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.2.3.4"
#define VER_MAJOR	1
#define VER_MINOR	2
#define VER_RELEASE	3
#define VER_BUILD	4
#define COMPANY_NAME	"MazeIcon"
#define FILE_VERSION	"1.2.3.4"
#define FILE_DESCRIPTION	"LAVA CONKER THE SQUIRREL"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"This is a No Skidded Malware"
#define PRODUCT_VERSION	"1.2.3.4"

#endif /*STRUCTDESTR_PRIVATE_H*/
